site_url: https://blog.wasd.fi
display_url: https://blog.wasd.fi
backend:
  name: github
  repo: msrn/blog.wasd.fi
  branch: master
  base_url: https://sveltia-cms-auth.nahkaz.workers.dev/
media_folder: static/img
public_folder: /img
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, fi]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    path: '{{year}}/{{month}}/{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    slug: "{{slug}}"
    i18n: true
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' , i18n: true}
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true, i18n: true}
      - { label: 'Slug', name: 'slug', widget: 'string' , i18n: false, required: false}
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD', default: '' , i18n: duplicate, required: false}
      - { label: 'Category', name: 'categories', widget: 'list', i18n: duplicate}
      - { label: 'Tags', name: 'tags', widget: 'list', i18n: duplicate}
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true}
  - name: 'pages'
    label: 'Pages'
    i18n: true
    files:
      - label: 'About Page'
        name: 'about'
        file: 'content/about/_index.{{locale}}.md'
        i18n: true
        fields:
          - { label: 'Title', name: 'title', widget: 'string' , i18n: true}
          - { label: 'Draft', name: 'draft', widget: 'boolean', default: true}
          - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD', default: '' , i18n: duplicate}
          - { label: 'Body', name: 'body', widget: 'markdown', i18n: true}